services:
  postgres:
    container_name: sduchat-postgres
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sduchat
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U k_app -d sduchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  sdu-chat-backend:
    container_name: sduchat-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sduchat
      SPRING_DATASOURCE_USERNAME: k_app
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  
