version: "3.8"

services:
  postgres:
    container_name: sduchat-postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sduchat
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
  
